SELECT
	-- IDs de documento
	DOCTOS_CC.DOCTO_CC_ID,
	IMPORTES_DOCTOS_CC.DOCTO_CC_ACR_ID,
	IMPORTES_DOCTOS_CC.IMPTE_DOCTO_CC_ID,
	USOS_ANTICIPOS_CC.ANTICIPO_CC_ID,
	-- IDs de cuenta
	DOCTOS_CC.CLIENTE_ID,
	CLIENTES.TIPO_CLIENTE_ID,
	CLIENTES.VENDEDOR_ID,
	CLIENTES.MONEDA_ID,
	DOCTOS_CC.COND_PAGO_ID,
	DOCTOS_CC.CONCEPTO_CC_ID,
	-- Variables de cuenta
	CLIENTES.NOMBRE AS NOMBRE_CLIENTE,
	TIPOS_CLIENTES.NOMBRE AS TIPO_CLIENTE,
	MONEDAS.CLAVE_FISCAL AS MONEDA,
	CONDICIONES_PAGO.NOMBRE AS CONDICIONES,
	VENDEDORES.NOMBRE AS VENDEDOR,
	CLIENTES.ESTATUS AS ESTATUS_CLIENTE,
	CLIENTES.LIMITE_CREDITO,
	-- Variables transaccionales
	CONCEPTOS_CC.NOMBRE AS CONCEPTO,
	DOCTOS_CC.FOLIO,
	-- Variables de tiempo
	IMPORTES_DOCTOS_CC.FECHA AS FECHA_EMISION,
	VENCIMIENTOS_CARGOS_CC.FECHA_VENCIMIENTO,
	DOCTOS_CC.HORA,
	-- Logica de negocio
	DOCTOS_CC.SISTEMA_ORIGEN,
	DOCTOS_CC.NATURALEZA_CONCEPTO,
	IMPORTES_DOCTOS_CC.CANCELADO,
	IMPORTES_DOCTOS_CC.APLICADO,
	-- Variables cualitativas
	DOCTOS_CC.DESCRIPCION,
	-- Variables numericas
	USOS_ANTICIPOS_CC.TIPO_USO AS TIPO_USO_ANTICIPO,
	CASE
		WHEN DOCTOS_CC.NATURALEZA_CONCEPTO = 'C' THEN IMPORTES_DOCTOS_CC.IMPORTE
		ELSE 0
	END AS CARGOS,
	CASE
		WHEN DOCTOS_CC.NATURALEZA_CONCEPTO = 'R' THEN IMPORTES_DOCTOS_CC.IMPORTE
		ELSE 0
	END AS ABONOS,
	IMPORTES_DOCTOS_CC.TIPO_IMPTE,
	IMPORTES_DOCTOS_CC.IMPORTE,
	IMPORTES_DOCTOS_CC.IMPUESTO,
	-- Auditoria de datos
	DOCTOS_CC.USUARIO_CREADOR,
	DOCTOS_CC.FECHA_HORA_CREACION,
	DOCTOS_CC.USUARIO_ULT_MODIF,
	DOCTOS_CC.FECHA_HORA_ULT_MODIF,
	DOCTOS_CC.USUARIO_CANCELACION,
	DOCTOS_CC.FECHA_HORA_CANCELACION
FROM DOCTOS_CC
LEFT JOIN CLIENTES ON DOCTOS_CC.CLIENTE_ID = CLIENTES.CLIENTE_ID
LEFT JOIN TIPOS_CLIENTES ON CLIENTES.TIPO_CLIENTE_ID = TIPOS_CLIENTES.TIPO_CLIENTE_ID
LEFT JOIN VENDEDORES ON CLIENTES.VENDEDOR_ID = VENDEDORES.VENDEDOR_ID
LEFT JOIN MONEDAS ON CLIENTES.MONEDA_ID = MONEDAS.MONEDA_ID
LEFT JOIN CONCEPTOS_CC ON DOCTOS_CC.CONCEPTO_CC_ID = CONCEPTOS_CC.CONCEPTO_CC_ID
LEFT JOIN VENCIMIENTOS_CARGOS_CC ON DOCTOS_CC.DOCTO_CC_ID = VENCIMIENTOS_CARGOS_CC.DOCTO_CC_ID
LEFT JOIN IMPORTES_DOCTOS_CC ON DOCTOS_CC.DOCTO_CC_ID = IMPORTES_DOCTOS_CC.DOCTO_CC_ID
LEFT JOIN USOS_ANTICIPOS_CC ON DOCTOS_CC.DOCTO_CC_ID = USOS_ANTICIPOS_CC.DOCTO_CC_ID
LEFT JOIN ANTICIPOS_CC ON USOS_ANTICIPOS_CC.ANTICIPO_CC_ID = ANTICIPOS_CC.ANTICIPO_CC_ID
LEFT JOIN CONDICIONES_PAGO ON DOCTOS_CC.COND_PAGO_ID = CONDICIONES_PAGO.COND_PAGO_ID
-- WHERE USOS_ANTICIPOS_CC.DOCTO_CC_ACR_ID IS NOT NULL
-- WHERE TIPOS_CLIENTES.TIPO_CLIENTE_ID IS NULL
-- WHERE ANTICIPOS_CC.ANTICIPO_CC_ID IS NULL
-- WHERE CLIENTES.TIPO_CLIENTE_ID IS NULL
-- WHERE IMPORTES_DOCTOS_CC.TIPO_IMPTE = 'A'
-- WHERE IMPORTES_DOCTOS_CC.DOCTO_CC_ACR_ID IS NULL
-- WHERE USOS_ANTICIPOS_CC.TIPO_USO IS NOT NULL
-- WHERE DOCTOS_CC.TIPO_CAMBIO > 1
-- WHERE CLIENTES.NOMBRE LIKE '%EMPLEADOS%'
ORDER BY
	CLIENTES.NOMBRE ASC,
	IMPORTES_DOCTOS_CC.DOCTO_CC_ACR_ID ASC,
	DOCTOS_CC.DOCTO_CC_ID ASC,
	IMPORTES_DOCTOS_CC.FECHA DESC
;
